### ISSUE TITLE
sh: 1: cd: can't cd to contrib/satellite

### ISSUE THREAD

**Issue by ld-t** [sns3/sns3-satellite#44]
I compiled and generated the ns3 and SNS3 projects in VScode.  An error is prompted when running the executable generated by the scratch folder
**This is the cbr test file in sns3**
sh: 1: cd: can't cd to contrib/satellite
sh: 1: cd: can't cd to contrib/satellite
Installing traffic model on 1/1 UT users
--- sat-cbr-example ---
  Scenario used: simple
  PacketSize: 512
  Interval: 1s
  
At time 8s cbr application sent 512 bytes to 90.2.0.2 port 9 total Tx 512 bytes
At time +8.31503s packet sink received 512 bytes from 10.1.0.2 port 49153 total Rx 512 bytes
At time 9s cbr application sent 512 bytes to 90.2.0.2 port 9 total Tx 1024 bytes
At time 10s cbr application sent 512 bytes to 90.2.0.2 port 9 total Tx 1536 bytes

**This is the test file in ns3**
sh: 1: cd: can't cd to contrib/satellite
sh: 1: cd: can't cd to contrib/satellite
Scratch Simulator

**This is the comman line**
~/ns-3-dev/build/scratch$ ~/ns-3-dev/build/scratch/ns3.37-scratch-simulator-debug

**Comment by Kniyl** [comment]
Hi,

You will be better off using the `ns3` wrapper to build and run the modules. This will take care of environment variables and working directory for you. Check [the documentation](https://www.nsnam.org/docs/tutorial/html/getting-started.html#running-a-script) for more details.

On the other hand, running you commands from `~/ns-3-dev` rather than the `build/scratch` directory should work fine.

**Comment by ld-t** [comment]
thanks a lot
